name: Working with secrets

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Print the value of a secret
      run: echo ${{ secrets.GREETING }}
